### ISSUE TITLE
Integration request: opal-webpacker into eZii-jester-data/redux-os

### ISSUE THREAD

**Issue by eZii-jester-data** [isomorfeus/isomorfeus-framework#32]
**Isomorfeus Implementation**
* [x] ruby

**Your Question:**

search for "ezii-redux" on hub.docker

goal is to make three.rb working via webpacker/opal-webpacker.

**Comment by janbiedermann** [comment]
Hi @eZii-jester-data ,
would you be able to join isomorfeus slack or gitter to discuss your question?
Go to https://isomorfeus.com, join slack or gitter, #opal_webpack_loader channel.
(We can understand some foreign languages, even asian ones, if language would be your concern)

**Comment by eZii-jester-data** [comment]
Yes
